WARNING 2024-01-31 16:50:12,496 django.server Thread-1 (process_request_thread) 27724 basehttp basehttp.py 212 django.server log_message 8056 "GET /static/image/flag.jpeg HTTP/1.1" 404 1804
WARNING 2024-01-31 16:51:41,280 django.server Thread-6 (process_request_thread) 25784 basehttp basehttp.py 212 django.server log_message 8056 "GET /static/image/flag.jpeg HTTP/1.1" 404 1804
WARNING 2024-01-31 16:51:41,303 django.request Thread-5 (process_request_thread) 10984 log log.py 241 django.request log_response 8056 Not Found: /useraccount/systemcategories/{% static % 'image/flag.jpeg' }
WARNING 2024-01-31 16:51:41,307 django.server Thread-5 (process_request_thread) 10984 basehttp basehttp.py 212 django.server log_message 8056 "GET /useraccount/systemcategories/%7B%%20static%20%%20'image/flag.jpeg'%20%7D HTTP/1.1" 404 8746
WARNING 2024-01-31 16:51:42,287 django.server Thread-5 (process_request_thread) 10984 basehttp basehttp.py 212 django.server log_message 8056 "GET /static/image/flag.jpeg HTTP/1.1" 404 1804
WARNING 2024-01-31 16:51:42,311 django.request Thread-7 (process_request_thread) 2880 log log.py 241 django.request log_response 8056 Not Found: /useraccount/systemcategories/{% static % 'image/flag.jpeg' }
WARNING 2024-01-31 16:51:42,311 django.server Thread-7 (process_request_thread) 2880 basehttp basehttp.py 212 django.server log_message 8056 "GET /useraccount/systemcategories/%7B%%20static%20%%20'image/flag.jpeg'%20%7D HTTP/1.1" 404 8746
WARNING 2024-01-31 16:52:37,086 django.server Thread-7 (process_request_thread) 2880 basehttp basehttp.py 212 django.server log_message 8056 "GET /static/image/flag.jpeg HTTP/1.1" 404 1804
WARNING 2024-01-31 16:52:40,816 django.server Thread-8 (process_request_thread) 15440 basehttp basehttp.py 212 django.server log_message 8056 "GET /static/image/defult.png HTTP/1.1" 404 1807
WARNING 2024-01-31 16:52:40,816 django.server Thread-9 (process_request_thread) 23188 basehttp basehttp.py 212 django.server log_message 8056 "GET /static/image/writing-icon.svg HTTP/1.1" 404 1825
WARNING 2024-01-31 16:53:28,348 django.server Thread-11 (process_request_thread) 29988 basehttp basehttp.py 212 django.server log_message 8056 "GET /static/image/writing-icon.svg HTTP/1.1" 404 1825
WARNING 2024-01-31 16:53:28,348 django.server Thread-10 (process_request_thread) 7284 basehttp basehttp.py 212 django.server log_message 8056 "GET /static/image/defult.png HTTP/1.1" 404 1807
WARNING 2024-01-31 16:53:30,205 django.server Thread-12 (process_request_thread) 28920 basehttp basehttp.py 212 django.server log_message 8056 "GET /static/image/flag.jpeg HTTP/1.1" 404 1804
WARNING 2024-01-31 16:53:30,209 django.server Thread-13 (process_request_thread) 30520 basehttp basehttp.py 212 django.server log_message 8056 "GET /static/static/image/flag.jpeg HTTP/1.1" 404 1825
WARNING 2024-01-31 16:53:32,175 django.server Thread-15 (process_request_thread) 27016 basehttp basehttp.py 212 django.server log_message 8056 "GET /static/static/image/flag.jpeg HTTP/1.1" 404 1825
WARNING 2024-01-31 16:53:32,175 django.server Thread-14 (process_request_thread) 9300 basehttp basehttp.py 212 django.server log_message 8056 "GET /static/image/flag.jpeg HTTP/1.1" 404 1804
WARNING 2024-01-31 16:54:37,847 django.server Thread-16 (process_request_thread) 29944 basehttp basehttp.py 212 django.server log_message 8056 "GET /static/image/flag.jpeg HTTP/1.1" 404 1804
WARNING 2024-01-31 16:54:38,406 django.server Thread-17 (process_request_thread) 13132 basehttp basehttp.py 212 django.server log_message 8056 "GET /static/image/flag.jpeg HTTP/1.1" 404 1804
WARNING 2024-01-31 16:54:38,501 django.server Thread-18 (process_request_thread) 30276 basehttp basehttp.py 212 django.server log_message 8056 "GET /static/image/flag.jpeg HTTP/1.1" 404 1804
WARNING 2024-01-31 16:54:38,720 django.server Thread-19 (process_request_thread) 13780 basehttp basehttp.py 212 django.server log_message 8056 "GET /static/image/flag.jpeg HTTP/1.1" 404 1804
ERROR 2024-01-31 16:54:49,532 django.request Thread-20 (process_request_thread) 25052 log log.py 241 django.request log_response 8056 Internal Server Error: /useraccount/systemcategories/
Traceback (most recent call last):
  File "C:\Users\Raghad-windows\anaconda3\lib\site-packages\django\template\base.py", line 502, in parse
    compile_func = self.tags[command]
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Raghad-windows\anaconda3\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Raghad-windows\anaconda3\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Raghad-windows\anaconda3\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\Raghad-windows\Desktop\dev\SysDoc2\SysDoc2\useraccount\views.py", line 246, in system_categories
    return render(request,"user/systemcategories.html",{'belongs_to_group1': belongs_to_group1})
  File "C:\Users\Raghad-windows\anaconda3\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\Raghad-windows\anaconda3\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\Raghad-windows\anaconda3\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\Raghad-windows\anaconda3\lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\Raghad-windows\anaconda3\lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\Raghad-windows\anaconda3\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\Raghad-windows\anaconda3\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\Raghad-windows\anaconda3\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "C:\Users\Raghad-windows\anaconda3\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\Raghad-windows\anaconda3\lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    return parser.parse()
  File "C:\Users\Raghad-windows\anaconda3\lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\Raghad-windows\anaconda3\lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\Raghad-windows\anaconda3\lib\site-packages\django\template\loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
  File "C:\Users\Raghad-windows\anaconda3\lib\site-packages\django\template\base.py", line 504, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\Raghad-windows\anaconda3\lib\site-packages\django\template\base.py", line 565, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 3: 'static'. Did you forget to register or load this tag?
ERROR 2024-01-31 16:54:49,538 django.server Thread-20 (process_request_thread) 25052 basehttp basehttp.py 212 django.server log_message 8056 "GET /useraccount/systemcategories/ HTTP/1.1" 500 202830
WARNING 2024-01-31 16:54:56,819 django.server Thread-20 (process_request_thread) 25052 basehttp basehttp.py 212 django.server log_message 8056 "GET /static/image/flag.jpeg HTTP/1.1" 404 1804
WARNING 2024-01-31 17:40:46,010 django.request Thread-3 (process_request_thread) 7180 log log.py 241 django.request log_response 13048 Not Found: /useraccount/css/contact.css
WARNING 2024-01-31 17:40:46,010 django.server Thread-3 (process_request_thread) 7180 basehttp basehttp.py 212 django.server log_message 13048 "GET /useraccount/css/contact.css HTTP/1.1" 404 8601
WARNING 2024-01-31 17:46:50,874 django.request Thread-7 (process_request_thread) 11396 log log.py 241 django.request log_response 13048 Not Found: /useraccount/css/contact.css
WARNING 2024-01-31 17:46:50,890 django.server Thread-7 (process_request_thread) 11396 basehttp basehttp.py 212 django.server log_message 13048 "GET /useraccount/css/contact.css HTTP/1.1" 404 8601
